defaults: &defaults
    page_fetcher_timeout: 10
    page_fetcher_delay: 1
    fetch_interval: 30

production:
    <<: *defaults

development:
    <<: *defaults

test:
    <<: *defaults
    page_fetcher_delay: 0

