defaults: &defaults
    page_fetcher_timeout: 5
    page_fetcher_delay: 1
    fetch_interval: 10

production:
    <<: *defaults

development:
    <<: *defaults

test:
    <<: *defaults
    page_fetcher_delay: 0

